### PR TITLE
Added svg rendering support to ffmpeg 3.4 and higher in ubuntu distros

### PR DESCRIPTION
**Pull request by jnbelo**
As a follow up to #295 , this PR adds svg rendering support to ffmpeg 3.4 and higher in ubuntu distros:

- Followed the [librsvg's instructions](https://gitlab.gnome.org/GNOME/librsvg/-/blob/master/COMPILING.md) to build the library; 
- Was not yet able to complete the build for distros other than ubuntu;
- Added pip to fetch meson and ninja so, as a hopefully positive side effect, VMAF support was added to 1804 ubuntu images as well. This was done because librsvg's dependencies required a higher version than the one I was able to get via apt and it seems to be the [recommended way](https://github.com/mesonbuild/meson) to fetch meson and ninja, anyway.

Let me know if anything else is needed.

### CODE REVIEW

**Comment by jnbelo** [comment]
Already saw that the builds failed. I seems that something is missing from PATH, related to pixbuf. It is odd, though, as this particular problem never occurred locally. I'll check it out, though.

**Comment by higgins** [comment]
hey @jnbelo, any updates here? looking to enable this too

**Comment by jnbelo** [comment]
Hello @higgins. Unfortunately, the project I was working on dropped this requirement so it ended up going lower in my priorities list. Meant to try to get it to work eventually but simply didn't have the opportunity. 

If I have some time, I may try to tackle this but I doubt I'll be able to do it on the short term, as building and testing takes a considerable amount of time. Alternatively, feel free to pick up where I left off.

One thing, though, is that I later realized that, in the current implementation, it wasn't properly rendering if the svg files had images in them.

**Comment by higgins** [comment]
> Hello @higgins. Unfortunately, the project I was working on dropped this requirement so it ended up going lower in my priorities list. Meant to try to get it to work eventually but simply didn't have the opportunity.
> 
> If I have some time, I may try to tackle this but I doubt I'll be able to do it on the short term, as building and testing takes a considerable amount of time. Alternatively, feel free to pick up where I left off.
> 
> One thing, though, is that I later realized that, in the current implementation, it wasn't properly rendering if the svg files had images in them.

Thanks for the update, @jnbelo ! This actually got removed from our needs as well. Fine with the base image!
If ffmpeg ends up [supporting parse svg on stdin](http://ffmpeg.org/pipermail/ffmpeg-user/2022-April/054608.html), we might come back and pick this up though. ✌️

**Comment by jnbelo** [comment]
This PR is extremely outdated. No point in maintaining it.

**Pull request closed without merging**
