### PR TITLE
feat: add libzimg

### PR DESCRIPTION
**Pull request by emmanuelgeoffray**
Zimg is very useful to manipulate HDR videos. I expect it to be mandatory for all projects in the next few months.

I've isolated the zimg part in https://github.com/jrottenberg/ffmpeg/pull/318

I've tested the build 6.1/ubuntu2004.

### CODE REVIEW

**Comment by jrottenberg** [comment]
Looks very promising, thank you, can you rebase to get the build going ?

**Comment by jrottenberg** [comment]
No  `--enable-libzimg` on ffmpeg ?

**Comment by jrottenberg** [comment]
I've tested your branch, added the flag and got a successful build for one variant, so worth testing the rest.

**Comment by emmanuelgeoffray** [comment]
oops, forgot the flag, I've added it now @jrottenberg

**Comment by jrottenberg** [comment]
Great thank you !

**Comment by jrottenberg** [comment]
ok it worked great except on 2.8:
```
#41 [build 35/36] RUN          DIR=/tmp/ffmpeg && cd ${DIR} &&         ./configure         --disable-debug         --disable-doc         --disable-ffplay         --enable-avresample         --enable-fontconfig         --enable-gpl         --enable-libass         --enable-libbluray         --enable-libfdk_aac         --enable-libfreetype         --enable-libmp3lame         --enable-libopencore-amrnb         --enable-libopencore-amrwb         --enable-libopus         --enable-libtheora         --enable-libvidstab         --enable-libvorbis         --enable-libvpx         --enable-libwebp         --enable-libx264         --enable-libx265         --enable-libxvid         --enable-libzimg         --enable-libzmq         --enable-nonfree         --enable-openssl         --enable-postproc         --enable-shared         --enable-small         --enable-version3         --extra-cflags="-I/opt/ffmpeg/include"         --extra-ldflags="-L/opt/ffmpeg/lib"         --extra-libs=-ldl         --prefix="/opt/ffmpeg" &&         make clean &&         make &&         make install &&         make tools/zmqsend && cp tools/zmqsend /opt/ffmpeg/bin/ &&         make distclean &&         hash -r &&         cd tools &&         make qt-faststart && cp qt-faststart /opt/ffmpeg/bin/
#41 0.542 Unknown option "--enable-libzimg".
#41 0.542 See ./configure --help for available options.
```

Easy fix, thx again !

**Comment by emmanuelgeoffray** [comment]
> ok it worked great except on 2.8:
> 
> ```
> #41 [build 35/36] RUN          DIR=/tmp/ffmpeg && cd ${DIR} &&         ./configure         --disable-debug         --disable-doc         --disable-ffplay         --enable-avresample         --enable-fontconfig         --enable-gpl         --enable-libass         --enable-libbluray         --enable-libfdk_aac         --enable-libfreetype         --enable-libmp3lame         --enable-libopencore-amrnb         --enable-libopencore-amrwb         --enable-libopus         --enable-libtheora         --enable-libvidstab         --enable-libvorbis         --enable-libvpx         --enable-libwebp         --enable-libx264         --enable-libx265         --enable-libxvid         --enable-libzimg         --enable-libzmq         --enable-nonfree         --enable-openssl         --enable-postproc         --enable-shared         --enable-small         --enable-version3         --extra-cflags="-I/opt/ffmpeg/include"         --extra-ldflags="-L/opt/ffmpeg/lib"         --extra-libs=-ldl         --prefix="/opt/ffmpeg" &&         make clean &&         make &&         make install &&         make tools/zmqsend && cp tools/zmqsend /opt/ffmpeg/bin/ &&         make distclean &&         hash -r &&         cd tools &&         make qt-faststart && cp qt-faststart /opt/ffmpeg/bin/
> #41 0.542 Unknown option "--enable-libzimg".
> #41 0.542 See ./configure --help for available options.
> ```
> 
> Easy fix, thx again !

sorry for this.
Do you want me to fix it or are you going to do it ?

I guess the fix would be to make it conditional on the version in the section below
image

**Pull request merged**
