### PR TITLE
Adding openssl for wget

### PR DESCRIPTION
**Pull request by johnwyles**

### CODE REVIEW

**Comment by jrottenberg** [comment]
can you add it to the template file : https://github.com/jrottenberg/ffmpeg/blob/master/templates/Dockerfile-template.alpine#L37

I use curl extensively during the build, it uses https without issue.

**Comment by johnwyles** [comment]
I think we can close this PR - I was simply adding it but I do not want to bloat the image unnecessairly but it is pretty canned that folks use this line for `dockerize` in their `Dockerfile`:

```dockerfile
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz
```

**Comment by johnwyles** [comment]
I did update the PR in case you did want to add it after all though...

**Comment by johnwyles** [comment]
CLOSING.

**Pull request closed without merging**
