### PR TITLE
Added support for Netflix/vmaf projects `libvmaf`

### PR DESCRIPTION
**Pull request by bramswenson**
Compiles and works perfectly with ubuntu and 4.1. I haven't tried the rest of the build matrix. Thanks for all your work. Nice setup, easy to modify!

image

https://ffmpeg.org/ffmpeg-filters.html#libvmaf

### CODE REVIEW

**Comment by jrottenberg** [comment]
Looks good , if you rebase if should pass the checks fine.

**Comment by leandromoreira** [comment]
@jrottenberg was it incorporated already somehow? or is it open yet for libvmaf inclusion?

**Comment by jrottenberg** [comment]
it is still open @leandromoreira my attempt on #135 was to rebase but that failed, might need @bramswenson to give it a try, but it's quite old.

Core change seems manageable : https://github.com/jrottenberg/ffmpeg/pull/127/files#diff-c909d8c027fda6191f3386bc9f4a46e1R77-R89

**Comment by jrottenberg** [comment]
@bramswenson do you want to give it another try ? It was perfect, but it got lost in a rebase ; it still generates some interest though.

**Comment by jrottenberg** [comment]
fixed by https://github.com/jrottenberg/ffmpeg/pull/289

**Comment by leandromoreira** [comment]
thank you so much @jrottenberg

**Comment by jrottenberg** [comment]
Yep thank you @pdiaz

**Pull request closed without merging**
