### PR TITLE
 Remove cuda dev files from nvidia variants

### PR DESCRIPTION
**Pull request by ShaulMyplay**
seems like nvidia variants started getting bloated with about 2T of nvidia development files, this PR should fix it.

### CODE REVIEW

**Comment by jrottenberg** [comment]
oh interesting, was it that large ?
Let me see on the previous build

**Comment by jrottenberg** [comment]
indeed... but they always have been quite large. Do you mind adding a `docker images` step on 
https://github.com/jrottenberg/ffmpeg/blob/master/templates/azure.template#L18
&
https://github.com/jrottenberg/ffmpeg/blob/master/.gitlab-ci.yml#L48 ?

**Comment by ShaulMyplay** [comment]
Seems like it was added in this PR (https://github.com/jrottenberg/ffmpeg/pull/224)
Regarding docker image  step, not sure what I should add, I think this should replace the current variants.

**Comment by jrottenberg** [comment]
ah no problem I'll take care of that in another MR

**Pull request merged**
