### PR TITLE
Publish centos7 and centos8 base containers

### PR DESCRIPTION
**Pull request by hvindin**
I've also intentionally left the update.py broken (looking for centos to exclude some things) because as far as I can tell, centos actually works fine for things like libaom? presumably it just didn't work properly during a previous attempt so it was dropped from the containers in which it wouldn't build to get it out in some container.

I guess I'll see how the azure pipelines go, my very manually skimming through of this indicated that it was working ok.

### CODE REVIEW

**Comment by hvindin** [comment]
Woops, looks like the stuff that needs a more modern version of nasm just fails silently and then carries on...

I've updated the centos7 template to skip installing the nasm rpm from the centos repos (although from memory the fedora 27 rpm is compatible....) and to just build nasm from source to get v2.14.2, which should be sufficiently modern to build any of the dependencies which need nasm installed...

**Comment by hvindin** [comment]
I'm not sure why but the 3.2 build seems flakey... it's failing for centos8 which is identical to the previous version of the container called centos... otherwise it looks like the lower versions of ffmpeg seem to be turning up with problems that I would have expected to show up for all the versions, like conflicts for basic dependencies? I'll have a closer look when I'm not just idly poking at this on my phone, but it seems like there might be some underlying flakeyness with the centos builds... which would make sense given how out much weirdness el distros tend to have to make them "long term" supportable...

**Comment by hvindin** [comment]
Well that's something... @jrottenberg turns out you can't build ffmpeg 3.2 on centos:8 without either compiling a different crypto library or really getting in there and patching some source code, openssl changed a lot of interfaces in the 1.1.0 version and centos:8 has 1.1.1 vs centos:7 which is on 1.0.2

From what I can see all the builds of ffmpeg 3.2 on centos:8 have actually failed silently, but it would seem that the pipelines still pass because running the container "jrottenberg/ffmpeg:3.2-centos" after a docker build has failed with just pull the old version of that container from docker hub, which will mask the failure.

Pulling jrottenberg/ffmpeg:3.2-centos _now_ pulls a centos:7 container.

It looks as though supporting  3.2 releases on _any_ centos base will need a centos:7 base, but with a lot of the recently merged pull requests they won't necessarily work immediately on centos:8 (well... they do with the commits in this branch, but that's kind of abusing the build container a bit).

It seems like there a few options here:
1. Revert the centos container to a centos:7 base, and just work around any forward compatibility issues as they come up
2. Force forward with the centos:8 base and drop ffmpeg:3.2 out of the respository
3. Get _really_ involved in the ffmpeg build and either throw in a different crypto library to use generically across all distros
4. Patch ffmpeg 3.2 in the centos container to use openssl 1.1.x properly with it's updated APIs

I'd be tempted to say that option 3 is probably the safest option but it's probably also the most painful to implement, option 2 is probably the easiest, or option 1 is probably ok if you were to take the centos7 Dockerfile template from this PR, and option 4 probably strays a fair bit from the goal of this repository given that once you start patching the ffmpeg source you aren't really "compiling FFmpeg from sources following instructions from the Compilation Guide.", because you're rewriting the sources.

Although, the arguably bigger problem here is that the pipelines pass if a version has _ever_ passed successfully, not if the current version passes successfully.

**Comment by hvindin** [comment]
Was that last commit a bit of a shim to just make centos7 _and_ centos8 containers work? kind of.

Will it practically work? I think so.

🙂

**Comment by hvindin** [comment]
So having tested everything I've touched locally it does seem that this PR fixes #217 in so far as it produces a centos7 container as well as a centos8 container, and both seem to work successfully.

It does have the drawback of not building a ffmpeg 3.2 container for centos:8, but looking at the pipeline history - there's _never_ a centos container being successfully built for ffmpeg 3.2, so at least this PR also provides a mechanism to exclude the 3.2-centos8 container from attempting to build given that it's just not compatible without a reasonable amount more work.

Because I've not fixed up the update.py script to exclude the --enable-libaom flag from centos7 and centos8 containers it will actually leave it and it seems to work fine? So this PR _also_ fixes #219 as well.

I've got another branch that should fix the subtle failures when there is a catastrophic build failure, but I'll wait until the builds for this one are finished to create the PR for it to avoid ending up with an odd "multiple builds trying to run at once" thing that happened last time I created two PR's at the same time.

**Comment by jrottenberg** [comment]
sorry a bit late, catching up....


it's nice but I'm worried adding new variants (distribution version) will not scale, we will have corner case like 3.2 on centos7 to be skipped, etc 
Let me think about it, if we do it, I can smell having to support ubutu:20.04 ,  18.04 and 16:04 The LTS

**Comment by jrottenberg** [comment]
looks good, can you rebase ?

**Comment by hvindin** [comment]
The LTS thing is definitely something I was thinking would become a problem, but it occurred to me that there are two things that seem like they might make it a good idea:
1. If offering different distros as bases then that should probably be extended out as far as is logical, especially for LTS releases I can imagine situations where people would want to LTS version to be available. Otherwise - why not _just_ publish a scratch image?
2. Adding in the ability to exclude variants/versions which don't play nice by default means that in cases like the centos8 v3.2 incompatibility where it looks like it would just be a huge pain to make it work properly then they can jusy be excluded. But for things which just sort of fall out of the keyboard when you type and just work as expected, it seems reasonable to make them available. And if someone really wants a version that is in the excludes list then it's up to them to do the work to get it building successfully.

Just my 2¢ but probably something that needs consideration I guess.

Will get cracking in that rebase 🙂

**Comment by hvindin** [comment]
Assuming that something else doesn't fail with the fontconfig change (to be honest I didn't actually test it, I just rebased, squashed some commits and pushed 😕) then this should be all good to re-review.

**Comment by hvindin** [comment]
Aha, not 10 minutes ago I was thinking "wait, won't pushing centos7 and centos8 containers mean that anyone hoping to get an update by pulling the latest centos container will suddenly have a problem?"

I think that I have a solution that as well so backwards compatibility is maintained. Let me just make some changes and do a little bit of testing to see how it works 🙂

**Comment by hvindin** [comment]
Ok, let's see how this goes.

I've added a `parent` attribute to all the variants. This change will hopefully cause the publication of a container with the `parent` tag as well.

So, for example, with the centos container for ffmpeg 3.2 the centos7 tag will still get published, but because centos7 is the only centos variant for 3.2 it will also get published with the centos tag, meanwhile all the other centos variants will be the centos8 version.

**Comment by hvindin** [comment]
Changes look like they good, sadly the docker push doesn't run from branch builds so the re-tagging and pushing the relevant container for the unversioned OS isn't happening in the tests, but the logic is fairly straight forward.

**Comment by jrottenberg** [comment]
very nice, thank you !

**Pull request merged**
