### PR TITLE
Newest ffmpeg version

### PR DESCRIPTION
**Pull request by qmfrederik**
The build break with the latest version of FFmpeg seems to be resolved by https://github.com/FFmpeg/FFmpeg/commit/b69ea742ab23ad74b2ae2772764743642212a139, so download that as a patch and apply it.

Let's see whether Travis likes it.

### CODE REVIEW

**Comment by jrottenberg** [comment]
🤞

**Comment by qmfrederik** [comment]
In a nutshell:
- There's a build break in 4.0.3, and https://github.com/FFmpeg/FFmpeg/commit/b69ea742ab23ad74b2ae2772764743642212a139.patch fixes this. Apply that patch
- aom uses [some odd logic](https://aomedia.googlesource.com/aom/+/v1.0.0/build/cmake/version.cmake) to determine the version number. By default, it will use Git. If you download a tarball, it will inspect the changelog. But the changelog lists the last version as 0.1, though it really is 1.0. Hence, pkg-config will detect version 0.1 but ffmpeg requires version 1.0. The easy fix is to do a git clone

**Comment by qmfrederik** [comment]
I think the two CentOS failures are flakes because of network connectivity issues. I can't restart them, unfortunately.

**Comment by jrottenberg** [comment]
fantastic ! Thank you very much

**Pull request merged**
