### PR TITLE
Added VMAF for ffmpeg 4.3 on some of the templates.

### PR DESCRIPTION
**Pull request by pdiaz**
This does add VMAF support to some of the distribution templates, as it's using the latest version of VMAF is only enabled on version 4.3.

### CODE REVIEW

**Comment by pdiaz** [comment]
@jrottenberg This PR does add the latest version of Netflix/vmaf to ffmpeg 4.3 and on ubuntu 20.04. I've seen other attempts to add support for it here but they appear somehow abandoned ( #127 #139 and  #258 )

This build failed on one of the distributions on which I haven't made any substantial changes so seems to fail for some other reason. I made some other tests that have not being pushed here to support ubuntu 18.04 but I haven't tried to implement it for the others.

What would you require to merge this? How can I help you?

**Comment by jrottenberg** [comment]
That looks very good, let me check/restart the failed builds, could be from a flaky runner.

Thank you!

**Comment by jrottenberg** [comment]
Yep, some part of a flaky build, I need to put some retry on the azure pipeline, doesn't seem available yet : https://developercommunity.visualstudio.com/t/rerun-failed-build-taskstep/365697#T-N1382773

**Comment by pdiaz** [comment]
Great! Thanks!

**Pull request merged**
