### PR TITLE
fix ffmpeg filter drawtext on the containers

### PR DESCRIPTION
**Pull request by jsheffie**
## Fix summary 

resolves: #412 

<details><summary>Problems Before Change</summary>
### Summary of current problems

| Image | Current state |
| --- | --- |
| jrottenberg/ffmpeg:7.1-ubuntu2404 | `Filter not found` |
| jrottenberg/ffmpeg:7.1-ubuntu2404-edge | `Filter not found` |
| jrottenberg/ffmpeg:6.1.2-ubuntu2404 | `Filter not found` |
| jrottenberg/ffmpeg:6.1.2-ubuntu2404-edge | `Filter not found` |
| jrottenberg/ffmpeg-7.1-nvidi2404 | `Cannot find a valid font for the family Sans` |
| jrottenberg/ffmpeg:7.1-alpine320 | `Filter not found` |
| jrottenberg/ffmpeg:7.1-scratch320 | `Filter not found` |
| jrottenberg/ffmpeg:7.1-vaapi2404 | `Filter not found` |
</details>

- added `enable-libharfbuzz`, `enable-libfontconfig`, `enable-libfribidi` to ffmpeg build conf.
- added `COPY` `/usr/share/fonts`,  `/usr/share/fontconfig`, `/usr/bin/fc-*` the final docker stage for fontconfig support.
- added `fontconfig` to the packages. ( for completeness ) 

- Os flavors: 
    - [x]  `<ffmpeg-ver>-ubuntu2404`
    - [x] `<ffmpeg-ver>-ubuntu2404-edge`
    - `<ffmpeg-ver>-vaapi2404`  ( does not work here 🤷‍♂️ , may need to be a separate PR )
    - [x] `<ffmpeg-ver>-nvidia2404`
    - [x] `<ffmpeg-ver>-alpine320`
    - [x] `<ffmpeg-ver>-scratch320`

Here is an example video with the drawtext used, to draw the word `Fire !`

https://github.com/user-attachments/assets/7f66444a-c9bc-4909-8c51-0fe2ab28a0ab

Convert video to smaller video
```
docker run --rm -v $(pwd):$(pwd) -w $(pwd) --platform="linux/amd64" ffmpeg-7.1-ubuntu2404-desktop-build:latest -i IMG_5428.MOV -ss 00:00:02 -t 00:00:01.5 -vf scale=iw/2:-2 -c:v libx264 -c:a copy outfile/solo_stove_slow_mo.mp4
```
Now add some text using ffmpeg `-vf "drawtext=text='Fire !'`
```
docker run --rm -v $(pwd):$(pwd) -w $(pwd) --platform="linux/amd64" ffmpeg-7.1-ubuntu2404-desktop-build:latest -i outfile/solo_stove_slow_mo.mp4 -vf "drawtext=text='Fire !':fontcolor=orange:fontsize=48:x=(w-text_w)/2:y=(h-text_h)/4" outfile/solo_stove_slow_mo_w_text.mp4
```

additional details are here: https://github.com/jrottenberg/ffmpeg/issues/412#issuecomment-2466497544

### CODE REVIEW

**Comment by jsheffie** [comment]
@jrottenberg @Gwemox @thiagoTeams This PR is ready-for-review and  fixes the `drawtext` problem for
- ffmpeg versions: `7.1`, `7.02`, `6.1.2`
- Os flavors: 
    - [x]  `<ffmpeg-ver>-ubuntu2404`
    - [x] `<ffmpeg-ver>-ubuntu2404-edge`
    - [ ] `<ffmpeg-ver>-vaapi2404` ( does not work here 🤷‍♂️ , may need to be a separate PR )
    - [x] `<ffmpeg-ver>-nvidia2404`
    - [x] `<ffmpeg-ver>-alpine320`
    - [x] `<ffmpeg-ver>-scratch320`

**Comment by jsheffie** [comment]
that failed build on scratch320 for 7.0.2 should build just fine ( I suspect this was just a azure hickup ) 
It built successful before... must be close to the build timeout max of an hour...

**Comment by jsheffie** [comment]
@jrottenberg I stimulated a new build. They all built now.
Note: They had all built before,  but then I got the scratch320 timeout on a build. 
Might need to look into making the scratch build quicker in the future,
if this build problem persists... my gut says it was a builder hickup. ( that made it slow )

**Review by jrottenberg — APPROVED** [review]

**Comment by jrottenberg** [comment]
Thank you again !

**Comment by Gwemox** [comment]
Thank you @jsheffie ! 
I'll be testing these new images soon.

**Pull request merged**
