### PR TITLE
Changed method for get count proc

### PR DESCRIPTION
**Pull request by jidckii**

### CODE REVIEW

**Comment by jrottenberg** [comment]
ah nice, let's see if it passes on all variants, it is definitely cleaner.

I would swear I was using nproc at some point and reverted to grep, but let's see

**Comment by jrottenberg** [comment]
nevermind it's for the ci... yeah should be fine, do you mind updating azure.yml as well ?

**Comment by jidckii** [comment]
> nevermind it's for the ci... yeah should be fine, do you mind updating azure.yml as well ?
Oh yeah, did not see the ci file for azure))
Now I will add

**Comment by jidckii** [comment]
Done
Another question, why do you add +1?
`$(($(nproc) + 1))`

**Comment by jrottenberg** [comment]
I went back to history... that setting was in the Dockerfile, and alpine bare didn't have nproc, simpler to use grep. As for the extra one, it's making the assumption that on any compilation, if all core are busy there is most likely one waiting on io, not actually all of them 'computing', so that extra thread was to get most performance out of the compilation by overloading it nicely, but it could be cargo cult, it doesn't hurt too much either way, but that guy is with you : https://blogs.gentoo.org/ago/2013/01/14/makeopts-jcore-1-is-not-the-best-optimization/

While you're on it, let's make it _$(nproc)_

**Comment by jidckii** [comment]
1 more optiongetconf _NPROCESSORS_ONLN

**Pull request merged**
