### PR TITLE
bring nvidia2004 up2date with nvidia-headers and cuda containers

### LINKED ISSUE #314: nvidia2004 4.4 is using 1804 image to build
https://github.com/jrottenberg/ffmpeg/blob/master/docker-images/4.4/nvidia2004/Dockerfile#L9

If I switch it out, ffmpeg doesn't build.

Here's the error on rebuild:

Step 70/80 : RUN         DIR=/tmp/ffmpeg && mkdir -p ${DIR} && cd ${DIR} &&         ./configure         --disable-debug         --disable-doc         --disable-ffplay         --enable-shared         --enable-avresample         --enable-libopencore-amrnb         --enable-libopencore-amrwb         --enable-gpl         --enable-libass         --enable-fontconfig         --enable-libfreetype         --enable-libvidstab         --enable-libmp3lame         --enable-libopus         --enable-libtheora         --enable-libvorbis         --enable-libvpx         --enable-libwebp         --enable-libxcb         --enable-libx265         --enable-libxvid         --enable-libx264         --enable-nonfree         --enable-openssl         --enable-libfdk_aac         --enable-postproc         --enable-small         --enable-version3         --enable-libbluray         --enable-libzmq         --extra-libs=-ldl         --prefix="${PREFIX}"         --enable-libopenjpeg         --enable-libkvazaar         --enable-libaom         --extra-libs=-lpthread         --enable-libsrt         --enable-libaribb24         --enable-nvenc         --enable-cuda         --enable-cuvid         --enable-libnpp         --extra-cflags="-I${PREFIX}/include -I${PREFIX}/include/ffnvcodec -I/usr/local/cuda/include/"         --extra-ldflags="-L${PREFIX}/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib32/" &&         make &&         make install &&         make tools/zmqsend && cp tools/zmqsend ${PREFIX}/bin/ &&         make distclean &&         hash -r &&         cd tools &&         make qt-faststart && cp qt-faststart ${PREFIX}/bin/
 ---> Running in 8eee3942b8e0
ERROR: libnpp not found

### PR DESCRIPTION
**Pull request by csreynolds**
Will fix #314 

verified on:
host machine: fedora34
docker-ce-20.10.8-3.fc34.x86_64
nvidia-docker2-2.5.0-3.noarch
nvidia-driver-470.63.01-2.fc34.x86_64
cuda-11.4.0-1.fc34.x86_64
VGA compatible controller: NVIDIA Corporation GP106GL [Quadro P2000] (rev a1)

```
INPUT="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
OUTPUT="output.mkv"
docker build . -t nvidia-ffmpeg-2004
docker run --privileged --gpus all -v $(pwd):$(pwd) -w $(pwd) nvidia-ffmpeg-2004 -hwaccel cuvid -c:v h264_cuvid -i ${INPUT} -vf scale_npp=1280:-1 -c:v h264_nvenc -b:v 2048k  -y ${OUTPUT}
```

### CODE REVIEW

**Comment by vade** [comment]
Thanks for this!

**Comment by jrottenberg** [comment]
Oh that's great, thank you , definitely a worthy change, can you make it to https://github.com/jrottenberg/ffmpeg/blob/master/templates/Dockerfile-template.nvidia2004#L9 so other ffmpeg versions can benefit of it.

See https://github.com/jrottenberg/ffmpeg/blob/master/README.md#contribute

**Comment by csreynolds** [comment]
> Oh that's great, thank you , definitely a worthy change, can you make it to https://github.com/jrottenberg/ffmpeg/blob/master/templates/Dockerfile-template.nvidia2004#L9 so other ffmpeg versions can benefit of it.
> 
> See https://github.com/jrottenberg/ffmpeg/blob/master/README.md#contribute

Done. Wasn't sure if older versions of ffmpeg would build correctly with the new cuda and headers. We'll see soon!

**Comment by jrottenberg** [comment]
Almost, can you run `./update.py` to regenerate all the dockerfiles ?

**Comment by csreynolds** [comment]
> Almost, can you run `./update.py` to regenerate all the dockerfiles ?

My bad. I incorrectly assumed running the update script happened during builds.

**Comment by jrottenberg** [comment]
All good and thank you !

**Pull request merged**
