### PR TITLE
ADD rockylinux8 Via update.py

### PR DESCRIPTION
**Pull request by arpagon**

### CODE REVIEW

**Comment by jrottenberg** [comment]
it looks good, but not sure why the ci didn't kick in, let me see before merging

**Comment by arpagon** [comment]
> Can you add a commit, to kick in the azure pipeline ?

Done... Is it a problem with CI/CD? I see you have GitLab and Azure. Which one do you really use?

**Comment by jrottenberg** [comment]
> > Can you add a commit, to kick in the azure pipeline ?
> 
> Done... Is it a problem with CI/CD? I see you have GitLab and Azure. Which one do you really use?


Thank you, yeah not sure what is going on with Azure pipeline not being triggered on fork builds ;-/

I used both, I was trying to slowly move the build to gitlab-ci but it's a bit too much cpu for the free plan.

**Comment by arpagon** [comment]
Let me know how can help?

**Review by jrottenberg — APPROVED** [review]

**Comment by jrottenberg** [comment]
I had to pull your changes on my remote ;-/

I'll fix that but at least checks are running now

**Comment by jrottenberg** [comment]
looks promising : https://github.com/jrottenberg/ffmpeg/pull/357

https://dev.azure.com/video-tools/ffmpeg/_build/results?buildId=550&view=logs&s=fe48a5e5-47a9-5a50-c8a8-3b820dff131f&j=e6484560-8c65-51ae-67a7-789e79106613

**Comment by arpagon** [comment]
🎉

**Pull request merged**
